chakra-ui/ark

- packages/vue/src/dialog/dialog.tsx
- packages/vue/src/dialog/use-dialog.ts
The type "Element" was breaking SSR for the dialog.
The context of the dialog was not reactive so i wrapped it inside a reactive to be able to spread it without losing reactivity.
Fixes issue : (#727)
> fix(ssr): replace Element prop type with Object

- packages/react/src/pin-input/pin-input.test.tsx
> test(react-pin-input): fix typo in test code 

- packages/react/src/radio-group/radio-group.test.tsx
Thank you for providing a good library.
I modified it because the actual test does not match the description of the test.
> test(react-radio-group): fix test description 

- packages/vue/docs/styling.mdx
> docs(vue): add styling doc for vue

- packages/react/CHANGELOG.md
- packages/react/src/toast/toast.stories.tsx
- packages/react/src/toast/toast.tsx
- packages/solid/CHANGELOG.md
- packages/solid/package.json
- packages/solid/src/toast/toast.tsx
- packages/vue/CHANGELOG.md
- packages/vue/src/toast/toast.tsx
closes Custom interactions with Toast via descriptions #1142
> fix: resolve an issue with custom rendered toasts

- scripts/src/prepare-release.ts
fix script prepare-release typo, change `pakcageName` to `packageName`
> fix: script prepare-release typo

- packages/solid/src/accordion/docs/accordion.mdx
- web/src/content/components/solid/accordion.mdx
Fixed Solid docs using react import.
> docs(solid): fix accordion import

- packages/frameworks/solid/src/date-picker/date-picker.stories.tsx
Current Solid DatePicker storybook has performance issues https://github.com/chakra-ui/ark/issues/1455
Using `<Index>` instead of `<For>` for the cells prevents the updates to cause DOM updates, leading to performance issues.
---
I also noticed that the `DatePickerGrid` id calls `createUniqueId()` that updates in the same way, not sure if it is intended behavior. I believe this does not have to keep updating?
https://github.com/chakra-ui/ark/blob/main/packages/frameworks/solid/src/date-picker/date-picker-grid.tsx#L17
> fix: solid datepicker

- packages/frameworks/vue/src/setup-test.ts
It will be used in next vue revision PRs
> test(vue): add get parts

- packages/scripts/package.json
- pnpm-lock.yaml
> Revert "chore(deps): update dependency ts-morph to v21"

- packages/scripts/package.json
- pnpm-lock.yaml
> revert "chore(deps): update dependency ts-node to v10.9.2"

- packages/frameworks/vue/src/accordion/accordion-item.tsx
- packages/frameworks/vue/src/color-picker/color-picker.tsx
- packages/frameworks/vue/src/combobox/combobox.tsx
- packages/frameworks/vue/src/date-picker/date-picker.tsx
- packages/frameworks/vue/src/dialog/dialog.tsx
- packages/frameworks/vue/src/hover-card/hover-card.tsx
- packages/frameworks/vue/src/menu/menu.tsx
- packages/frameworks/vue/src/popover/popover.tsx
- packages/frameworks/vue/src/presence/use-presence.ts
- packages/frameworks/vue/src/select/select.tsx
- packages/frameworks/vue/src/select/use-select.ts
- packages/frameworks/vue/src/tabs/tab-content.tsx
- packages/frameworks/vue/src/tooltip/tooltip.tsx
I think this might be a way to solve the usePresence type
> fix(vue): usePresence types

- packages/website/src/content/types/react/toast.types.json
- packages/website/src/content/types/solid/toast.types.json
- packages/website/src/content/types/vue/toast.types.json
I fixed typos in documents of Toast component.
> fix(website): fixed typos in documents of Toast component

- packages/frameworks/vue/src/accordion/accordion-root.tsx
- packages/frameworks/vue/src/color-picker/color-picker-root.tsx
- packages/frameworks/vue/src/combobox/combobox-root.tsx
- packages/frameworks/vue/src/date-picker/date-picker-root.tsx
- packages/frameworks/vue/src/dialog/dialog-root.tsx
- packages/frameworks/vue/src/hover-card/hover-card-root.tsx
- packages/frameworks/vue/src/menu/menu-root.tsx
- packages/frameworks/vue/src/popover/popover-root.tsx
- packages/frameworks/vue/src/select/select-root.tsx
- packages/frameworks/vue/src/tabs/tabs-root.tsx
- packages/frameworks/vue/src/tooltip/tooltip-root.tsx
> fix(vue): emits warn

- packages/website/src/components/docs/story.astro
> fix(website): stories bug

- packages/frameworks/react/CHANGELOG.md
- packages/frameworks/react/src/date-picker/use-date-picker.ts
- packages/frameworks/solid/CHANGELOG.md
- packages/frameworks/solid/src/date-picker/use-date-picker.ts
- packages/frameworks/vue/CHANGELOG.md
- packages/frameworks/vue/src/date-picker/date-picker.props.ts
- packages/frameworks/vue/src/date-picker/use-date-picker.ts
- packages/website/src/content/types/react/date-picker.types.json
- packages/website/src/content/types/solid/date-picker.types.json
- packages/website/src/content/types/vue/date-picker.types.json
This PR parses the min and max props for the date picker component.
> fix: parse min and max date values props for date picker

- packages/react/src/components/qr-code/examples/error-correction.tsx
- packages/react/src/components/qr-code/examples/with-overlay.tsx
- packages/solid/src/components/qr-code/examples/error-correction.tsx
- packages/solid/src/components/qr-code/examples/with-overlay.tsx
- packages/vue/src/components/qr-code/examples/error-correction.vue
- packages/vue/src/components/qr-code/examples/with-overlay.vue
- website/src/content/pages/components/qr-code.mdx
Add error correction section to qrcode docs
> docs(qrcode): error correction

- website/src/content/showcases.json
RELAND (https://reland.com.br) uses both Ark UI and Panda CSS
> docs: add reland in showcase

- packages/react/src/components/field/use-field.ts
This PR should resolve https://github.com/chakra-ui/ark/issues/2646
> fix(react): resolve a rules of hooks issue with useField

- packages/vue/src/components/dialog/examples/lazy-mount.vue
> docs(vue): fix typo

- packages/anatomy/src/steps/index.ts
- packages/react/src/components/steps/index.ts
- packages/react/src/components/steps/steps.anatomy.ts
- packages/solid/src/components/steps/index.ts
- packages/solid/src/components/steps/steps.anatomy.ts
- packages/vue/src/components/steps/index.ts
- packages/vue/src/components/steps/steps.anatomy.ts
Noticed that it wasn't reexported from zag!
> fix: export steps anatomy

- website/package.json
Reverts chakra-ui/ark#2856
Probably introduced #2868
> Revert "chore(deps): update dependency next to v14.2.8"

- packages/vue/src/components/frame/frame.vue
Closes https://github.com/chakra-ui/ark/issues/2891
> [VUE] fix: use onCleanup arg for broader vue@3.x support

- website/src/demos/frame.demo.tsx
Fix frame dark mode demo
**Before**
**After**
> chore: fix frame demo

- website/src/demos/dialog.demo.tsx
Action buttons broke dialog style.
after fix
> fix(docs): fix dialog demo style

- packages/react/src/components/presence/use-presence.ts
- packages/react/src/components/tabs/examples/controlled.tsx
- packages/react/src/utils/use-debounce.ts
> fix(react): controlled tabs

- packages/react/src/components/highlight/examples/basic.tsx
- packages/svelte/src/lib/components/highlight/examples/basic.svelte
- website/src/content/pages/guides/styling.mdx
> chore: fix typos in docs

- packages/react/src/components/checkbox/use-checkbox-group.ts
- packages/react/src/components/rating-group/examples/read-only.tsx
- packages/solid/src/components/checkbox/use-checkbox-group.ts
- packages/vue/src/components/accordion/accordion.types.ts
- packages/vue/src/components/checkbox/use-checkbox-group.ts
- packages/vue/src/components/tags-input/tags-input.types.ts
- packages/vue/src/utils/dynamic.ts
- website/src/app/actions.ts
- website/src/app/api/lemon/webhook/route.ts
- website/src/components/example.tsx
- website/src/content/pages/components/accordion.mdx
- website/src/content/types/react/accordion.types.json
- website/src/content/types/react/tags-input.types.json
- website/src/content/types/solid/accordion.types.json
- website/src/content/types/solid/tags-input.types.json
- website/src/content/types/vue/accordion.types.json
- website/src/content/types/vue/tags-input.types.json
- website/src/demos/hover-card.demo.tsx
> chore: fix typos

- packages/vue/src/components/qr-code/examples/basic.vue
> fix(website): vue example typo

- website/src/app/blog/page.tsx
- website/src/lib/nav-links.ts
This PR adds the blog as a navbar item
> docs: add blog to nav bar

- packages/svelte/src/lib/components/angle-slider/angle-slider-context.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-control.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-hidden-input.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-label.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-marker-group.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-marker.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-root-provider.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-root.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-thumb.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider-value-text.svelte
- packages/svelte/src/lib/components/angle-slider/angle-slider.anatomy.ts
- packages/svelte/src/lib/components/angle-slider/angle-slider.stories.ts
- packages/svelte/src/lib/components/angle-slider/angle-slider.ts
- packages/svelte/src/lib/components/angle-slider/examples/basic.svelte
- packages/svelte/src/lib/components/angle-slider/examples/controlled.svelte
- packages/svelte/src/lib/components/angle-slider/examples/step.svelte
- packages/svelte/src/lib/components/angle-slider/index.ts
- packages/svelte/src/lib/components/angle-slider/use-angle-slider-context.ts
- packages/svelte/src/lib/components/angle-slider/use-angle-slider.svelte.ts
- packages/svelte/src/lib/components/index.ts
Add Angle Slider component for svelte
> feat(svelte): add angle slider component

- website/src/content/blog/design-system-accordion.mdx
This PR adds the new blog to the Design System Series - for Accordion.
> docs: add accordion blog

- packages/vue/src/components/combobox/examples/creatable.vue
> fix(vue/combobox): creatable example checked state not updating
