chakra-ui/ark

packages/react/docs/getting-started.mdx

thanks for maintaining awesome library
there is some type so I fixed it up

docs(react): fix typo

---

packages/react/src/tooltip/tooltip.test.tsx

Thank you for providing a good library.
I wrote a test code to verify that the `interactive` prop of the `tooltip` is working properly.
FYI : I thought the default value of the interactive option was false, but it was true. I hope this part is also specified in docs.😃

test(react): write test code for tooltip interactive prop

---

packages/vue/src/number-input/number-input-field.tsx

Removing an accidental inclusion of `slots` in `number-input-field` applied to an `input` wrapping it.

fix(vue/number-input-field): remove unneccessary slots

---

packages/vue/src/select/index.ts
packages/vue/src/select/select-context.ts
packages/vue/src/select/select-option.tsx
packages/vue/src/select/select.test.tsx
packages/vue/src/select/select.tsx
packages/vue/src/select/use-select.ts

PR to pass props from the Zag Select api through a scoped slot in the `Select` component.
- Exposes a `SelectContext` type to be used with `v-slot` for intellisense and auto-completion when exposing props from the api. 
- i.e. `<Select v-slot="{ isOpen }: SelectContext">`
This PR also fixes `SelectOption` where custom html was not being accepted in place of rendering the option label. The `getValidChildren` helper was constantly returning false here (especially if the slot just contains a string), so it has been removed.
Closes #826

refactor(vue/select): update api handling

---

website/src/components/navigation/sidebar/SidebarExternalLinks.tsx

---
When I hovered Siderbar's external link in the existing docs, I saw that there was no action other than the cursor changing, so I thought it would be bad for UX. 
So we changed the color of the link by adding css, which changes the color of the link when the external link of the Siderbar is hovered, to improve the UX.
At the time of hover, the color was designated as the same color as when the sub-side bar items were hovered.

feat(docs): SidebarExternalLinks hover css event add

---

website/src/theme/recipes/select.ts

When a focus event occurs in the part where the framework of docs is selected, 
a box shadow occurs, and we found a problem of cutting. 
I thought it was showing the border thickly using box-shadow, 
and I gave the box-shadow inward to solve the problem without leaving this UI. 
As a result, the size of the select does not change and the border does not appear to be cut.
[Problem Occurrence Link
](https://ark-ui.com/docs/react/overview/introduction)

fix(docs): website button shadow

---

website/src/components/docs/TableOfContent.tsx
website/src/lib/useScrollSpy.ts

There is a problem that when a page is scrolling, the appearance of the `Link` component inside the `TableOfContent` component does not change automatically.
This is because the `useScrollSpy` hook is not working properly. Instead of getting `"#" + item.slug` injected, we got `item.slug` injected and added `"#"` inside the hook.
Also, I assigned `item.slug` as the ID of Link, so that the `querySelector` works properly.

fix(docs): TableOfContent scrollspy doesn't work

---

website/src/components/navigation/navbar/Navbar.tsx

--- 
When I hovered main navigation in existing docs, I saw that there was no action other than the cursor changing, so I thought it would be bad for UX. 
So I changed the color of the link by adding css, which changes the color of the link when I hovered the navigation link, and improved the UX.

feat(docs): website main navigation hover event

---

packages/vue/src/carousel/carousel-next-slide-trigger.tsx
packages/vue/src/carousel/carousel-prev-slide-trigger.tsx
packages/vue/src/carousel/carousel.stories.vue
packages/vue/src/carousel/carousel.test.tsx

As previously reported, Prev/Next buttons were not being rendered correctly. In the meantime, found out that the merged attributes were also incorrectly bound — next trigger props were being merged to prev trigger. Added basic tests coverage (that's how I found out about the attributes issues).
Closes https://github.com/chakra-ui/ark/issues/1051

[vue/carousel] Fix Prev/Next buttons render

---

packages/vue/src/pagination/docs/pagination.mdx

this commit add ref attribute on vue pagination example

fix(docs): add missing ref implementation on vue pagination docs

---

packages/vue/src/dialog/dialog.tsx

fix missing `update:open` emits on dialog component. related issue https://github.com/chakra-ui/ark/issues/1035

fix(vue): add emit update:open on dialog component

---

packages/vue/src/dialog/use-dialog.ts

Adds the missing `onOpen` events which were originally added in #898 and then removed in #918

refactor(vue/dialog): Add missing onOpen events

---

packages/vue/src/select/docs/select.mdx

Fixed a little one word typo found in the docs for the vue select component

docs: fix typo in vue select component

---

packages/frameworks/react/CHANGELOG.md
packages/frameworks/react/src/editable/use-editable.ts

There is currently an issue in `@zag-js/editable` 0.21.0 where passing an object with a state value of `useState` and using the `<Editable />` component in controlled form does not control the value as desired.
You can see a demo below.
(Currently, the logic is set up so that the value is fixed at 10000, but you can see that any value above 10000 will be input).
- [demo](https://stackblitz.com/edit/stackblitz-starters-m4rdhb?file=src%2FApp.tsx,src%2Fstyle.css)
To fix this, modify the code for `zag` and `ark`.
In `zag`, we'll add logic to synchronize if the externally input value is different from the internal value.
- [zag PR](https://github.com/chakra-ui/zag/pull/883)
In `ark`, we apply `flushSync` to `onChange`.
If there is a better form, please let me know.
cc. @malangcat

chore(react): `<Editable />` flushsync onChange function

---

packages/website/package.json
packages/website/src/components/anatomy-image.tsx
packages/website/src/components/anatomy.astro
packages/website/src/content/components/accordion.mdx
packages/website/src/content/components/avatar.mdx
packages/website/src/content/components/checkbox.mdx
packages/website/src/content/components/combobox.mdx
packages/website/src/content/components/dialog.mdx
packages/website/src/content/components/editable.mdx
packages/website/src/content/components/hover-card.mdx
packages/website/src/content/components/menu.mdx
packages/website/src/content/components/number-input.mdx
packages/website/src/content/components/pagination.mdx
packages/website/src/content/components/pin-input.mdx
packages/website/src/content/components/popover.mdx
packages/website/src/content/components/radio-group.mdx
packages/website/src/content/components/range-slider.mdx
packages/website/src/content/components/rating-group.mdx
packages/website/src/content/components/segment-group.mdx
packages/website/src/content/components/select.mdx
packages/website/src/content/components/slider.mdx
packages/website/src/content/components/splitter.mdx
packages/website/src/content/components/switch.mdx
packages/website/src/content/components/tabs.mdx
packages/website/src/content/components/tags-input.mdx
packages/website/src/content/components/toast.mdx
packages/website/src/content/components/toggle-group.mdx
packages/website/src/content/components/tooltip.mdx
pnpm-lock.yaml

As I've checked, we don't have Zag icons for:
- Carousel
- Color Picker
- Date Picker
- Environment
- Presence
There are no components in Ark UI:
- File Upload
There are no pages in Ark UI:
- Nested Menu
There are no anatomies on Zag page:
- Splitter (`split-view` almost empty page hidden in sidebar)
in this case I've added own description, so please check this (if it's good then I'll add it in Zag docs)
There is no anatomy at all:
- Pressable

docs: add anatomies

---

packages/website/src/content/components/number-input.mdx

`number-input` component docs is out of date regarding the precision props available to set.
Looking at the story examples [this](https://github.com/chakra-ui/ark/blob/b8d44379fe07720f173b783fae25ce3e64f69e1b/packages/frameworks/react/src/number-input/number-input.stories.tsx#L40) is the correct way to use precision
[Preview link](https://ark-docs-git-fork-rodrigoslino-main-chakra-ui.vercel.app/docs/components/number-input)

update number-input precision doc

---

packages/website/src/components/marketing/examples.ts
packages/website/src/content/overview/getting-started.mdx

The `Slider.Thumb` component, which is used as an example in the [Getting Started page](https://ark-ui.com/docs/overview/getting-started), requires the `index` prop, so the example gets a type error. This PR adds the `index` prop to the example.
https://ark-ui.com/docs/components/slider

docs: add missing props in slider examples

---

packages/website/src/demos/menu.demo.tsx

I was playing with the example for the Menu component in the docs, and I realized that some items were unreachable when navigating with the keyboard and pressing their first letter.
It was caused by extra spaces in the item content. So this little PR fixes that by removing the extra spaces.

docs: fix keyboard navigation in Menu component

---

packages/frameworks/vue/src/accordion/accordion-item.tsx
packages/frameworks/vue/src/accordion/tests/accordion.test.tsx

This PR addresses the issue where setting the `disabled` prop for `Accordion.Root` to true was not propagating to the items.
In `Accordion.Item`, the `disabled` prop was declared with a default value of `false`, perpetually taking precedent when checking item state. This is because `getItemState` in the [Zag Accordion Connect](https://github.com/chakra-ui/zag/blob/305ac564f33c05a209d403dc2008984cc7520e17/packages/machines/accordion/src/accordion.connect.ts#L25) is running a nullish coalescing for `isDisabled` to obtain its value .
The default value still needs to be declared, but it should be `undefined` so the nullish coalescing returns false in the check and obtains that context's disabled value instead.
Also, remove the skip for the related test.

fix(vue/accordion-item): set default for `disabled` prop to `undefined`

---

packages/frameworks/vue/src/combobox/use-combobox.ts
packages/frameworks/vue/src/select/use-select.ts

In component Combobox, reactivity can be lost by directly deconstruct props. So I try to fix this by create `collection` in `context`, also Select.

fix(vue/collection): reactivity with collection

---

packages/frameworks/solid/src/select/use-select.ts

This PR fixed #2029 
- The `use-select` hook currently doesn't update the state machine of `zag-js` when `collectionOptions`'s props change.
- This PR make that hook register change in `collectionOptions`'s props including `items` props.
- Which in turn solve #2029

fix(solid): added reactivity to collection and context of use-select (#2029)

---

packages/frameworks/solid/src/combobox/use-combobox.ts

This PR apply to same fix from #2030 to the `Combobox` component.
The same bug (#2029) also appears in this component ([StackBlitz](https://stackblitz.com/edit/solidjs-templates-teegxc?file=src%2FApp.tsx))

fix(solid): add reactivity to collection and context of use-combobox

---

packages/frameworks/solid/package.json
packages/frameworks/solid/src/setup-test.ts
packages/frameworks/solid/vite.config.mts
pnpm-lock.yaml

The new vite plugin does a lot of automatic testing configuration out of the box, so let's remove superfluous stuff.

test(solid): update vite-plugin-solid to 2.8.3

---

packages/frameworks/react/src/portal.test.tsx
packages/frameworks/react/src/portal.tsx

Fixes #2154 and #1787
There were a lot of ways this could be solved, most of them are by working around `typescript`. I decided to push the most type-safe solution since `Portal`'s return type now gets inferred as `JSX.Element`, so the code will work on all versions of `@types/react@18`. The only downside is adding a `Fragment` without actually needing it. 
I also added some tests for the `Portal` component since there weren't any :)

fix(react): updates `Portal` to have backward compatibility

---

packages/website/src/content/components/select.mdx

Adds a section in the `Select` component docs page for TypeScript describing the caveat in having a Generic prop type in Vue.

docs(website): add typescript caveat disclaimer in select component page

---

packages/website/src/content/components/combobox.mdx

Adds a section in the `Combobox` component docs page for TypeScript describing the caveat in having a Generic prop type in Vue.

docs(website): add typescript caveat disclaimer in combobox component page

---

packages/frameworks/react/src/menu/menu-context.ts

Some types of menu contexts are currently set to `unknown`, and I don't really know why.
I've updated these types :
- `UseMenuReturn['api'] | undefined` for the `MenuContext`.
- `UseMenuReturn['machine'] | undefined` for the `MenuMachineContext`.

fix(menu): expose context types

---

packages/frameworks/react/src/create-split-props.ts
packages/frameworks/solid/src/create-split-props.ts

Just a small suggestion. 💙 
refactor EnsureKeys type for improved readability by removing nested ternary and unnecessary never type, which was not required for type safety.
If you encounter any issues, please leave a message. Thank you.

refactor(react): simplify ensureKeys type definition

---

packages/frameworks/vue/src/color-picker/color-picker-content.tsx
packages/frameworks/vue/src/combobox/combobox-content.tsx
packages/frameworks/vue/src/date-picker/date-picker-content.tsx
packages/frameworks/vue/src/dialog/dialog-backdrop.tsx
packages/frameworks/vue/src/dialog/dialog-content.tsx
packages/frameworks/vue/src/hover-card/hover-card-content.tsx
packages/frameworks/vue/src/menu/menu-content.tsx
packages/frameworks/vue/src/popover/popover-content.tsx
packages/frameworks/vue/src/select/select-content.tsx
packages/frameworks/vue/src/tabs/tab-content.tsx
packages/frameworks/vue/src/tooltip/tooltip-content.tsx
packages/website/src/content/types/vue/byte-format.types.json

This PR fixes: #2329
Also add missing `presenceProps` on other Vue components compared to the React components.
This fixes the close animations for those components:
- Color picker
- Combobox
- Date picker
- Dialog & Dialog backdrop
- Hover card
- Menu
- Popover
- Select
- Tabs
- Tooltip
Note: Not sure if it's correct that the close animations in Histoire are a bit different for some components then in the Ark docs.

fix(vue): add missing presenceProps for certain Vue components

---

website/src/components/color-mode-button.astro

Fix missing readable label on the theme switcher.

fix(docs): add missing theme switcher label

---

website/src/content/components/carousel.mdx
website/src/content/components/date-picker.mdx
website/src/content/components/number-input.mdx

fixes: #2421
and 2 other typo's

docs: fix typo carousel example

---

website/src/content/pages/components/collapsible.mdx

Docs showed animation for the accordion component :
```scss
@keyframes slideDown {
from { height: 0; }
to { height: var(--height); }
}
@keyframes slideUp {
from { height: var(--height); }
to { height: 0; }
}
[data-scope='accordion'][data-part='item-content'][data-state='open'] {
animation: slideDown 250ms;
}
[data-scope='accordion'][data-part='item-content'][data-state='closed'] {
animation: slideUp 200ms;
}
```
Instead of the accurate animation code :
```scss
@keyframes slideDown {
from { height: 0; }
to { height: var(--height); }
}
@keyframes slideUp {
from { height: var(--height); }
to { height: 0; }
}
[data-scope='collapsible'][data-part='content'][data-state='open'] {
animation: slideDown 250ms;
}
[data-scope='collapsible'][data-part='content'][data-state='closed'] {
animation: …
```

Fixed collapsible component animation documentation

---

packages/solid/src/components/date-picker/date-picker-table-cell.tsx

This fixes the issue where the `aria-selected` attribute wasn't updating when a cell was selected

fix(solid): `aria-selected` not update when selected

---

packages/react/CHANGELOG.md
packages/react/src/components/checkbox/checkbox-group.tsx
packages/solid/CHANGELOG.md
packages/solid/src/components/checkbox/checkbox-group.tsx
packages/vue/CHANGELOG.md
packages/vue/src/components/checkbox/checkbox-group.vue

Checkbox groups should have a `group` role.
https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox/

fix: Add missing `group` role to Checkbox Group

---

packages/react/CHANGELOG.md
packages/react/src/components/checkbox/checkbox-group.tsx
packages/react/src/components/checkbox/checkbox.stories.tsx
packages/react/src/components/checkbox/examples/group-with-form.tsx
packages/react/src/components/checkbox/examples/group.tsx
packages/react/src/components/checkbox/use-checkbox-group.ts
packages/solid/CHANGELOG.md
packages/solid/src/components/checkbox/checkbox-group.tsx
packages/solid/src/components/checkbox/examples/group.tsx
packages/solid/src/components/checkbox/use-checkbox-group.ts
packages/vue/CHANGELOG.md
packages/vue/src/components/checkbox/checkbox-group.types.ts
packages/vue/src/components/checkbox/examples/group.vue
packages/vue/src/components/checkbox/use-checkbox-group.ts
website/src/content/types/react/checkbox.types.json
website/src/content/types/solid/checkbox.types.json
website/src/content/types/vue/checkbox.types.json

Hi! I added a `name` prop to CheckboxGroup to set the name of all the checkboxes it holds to improve form submission usage. I'm not really sure if there are any tests to add. I updated the story examples to show that the input names are updated if the prop is set.
I'm not too well versed in vue nor solid, so please scrutinize my code heavily!
Also, I noticed that CheckboxGroup props take precedence over the props passed into a single `CheckboxRoot`. Is this on purpose?

feat: Add a name prop to CheckboxGroup

---

packages/react/CHANGELOG.md
packages/react/src/components/toast/index.ts
packages/solid/CHANGELOG.md
packages/solid/src/components/toast/index.ts
packages/vue/CHANGELOG.md
packages/vue/src/components/toast/index.ts

I need the CreateToasterReturn prop in my project. I figured other people may need it too. I don't see any harm in exposing it.

feat(react): expose CreateToasterReturn prop

---

website/src/components/navigation/navbar-container.tsx

This PR should fix: #2625 
I bumped the z-index of the navbar to 2, this will be higher than the z-index of the tabs (which is 1).

fix(docs): fix z-index of top navigation to 2

---

website/src/components/navigation/docs/docs-navbar.tsx

This PR should fix: https://github.com/chakra-ui/ark/issues/2625
and is addition to this PR: #2676 
Noticed the same behavior on the docs navbar on the mobile view.
I bumped the z-index of the docs navbar to 2, this will be higher than the z-index of the tabs (which is 1).

fix(docs): fix z-index of docs navbar to 2

---

packages/solid/src/components/select/select-hidden-select.tsx

The item type of Index component is `() => T`, we should call it to access the value.
Related: #2665

fix(solid): fix option value and disabled in hidden select

---

packages/vue/src/components/color-picker/color-picker-content.vue
packages/vue/src/components/color-picker/color-picker-positioner.vue
packages/vue/src/components/combobox/combobox-content.vue
packages/vue/src/components/combobox/combobox-positioner.vue
packages/vue/src/components/date-picker/date-picker-content.vue
packages/vue/src/components/date-picker/date-picker-positioner.vue
packages/vue/src/components/dialog/dialog-content.vue
packages/vue/src/components/dialog/dialog-positioner.vue
packages/vue/src/components/dialog/tests/dialog.test.ts
packages/vue/src/components/hover-card/hover-card-content.vue
packages/vue/src/components/hover-card/hover-card-positioner.vue
packages/vue/src/components/menu/menu-content.vue
packages/vue/src/components/menu/menu-positioner.vue
packages/vue/src/components/popover/popover-content.vue
packages/vue/src/components/popover/popover-positioner.vue
packages/vue/src/components/select/select-content.vue
packages/vue/src/components/select/select-positioner.vue
packages/vue/src/components/time-picker/time-picker-content.vue
packages/vue/src/components/time-picker/time-picker-positioner.vue
packages/vue/src/components/tooltip/tests/tooltip.test.ts
packages/vue/src/components/tooltip/tooltip-content.vue
packages/vue/src/components/tooltip/tooltip-positioner.vue

Resolves #2739.
As stated in the issue, any component with `Positioner` part has an issue with an exit animation, because `Presence` is used on the `Positioner` instead of a `Content`.
This PR fixes all of the related vue components. 
Code changes are made taking React implementation as an example and briefly tested in histoire stories.

fix(vue): presence of componets with `Positioner`

---

website/src/content/pages/components/tags-input.mdx

The `TagsInput` docs refers to a prop called `allowEditTag` which is superseded by `editable`.

docs: Update prop referenced in "Disable tag editing" section of TagsInput

---

website/src/components/marketing/hero.tsx

Fix a typo in the hero of the doc website where it stated `reat/plus` instead of `react/plus`.
(Guess this is my Hacktober PR 🫣)

fix(docs): fix typo in hero for react plus button

---

packages/react/src/components/fieldset/use-fieldset.ts

Current `useFieldset()` uses `useLayoutEffect()`, but `useLayoutEffect()` occurs warning in SSR. In `useField()`, this problem is already fixed as using `useSafeLayoutEffect()`.   
So I tried to fix `useFieldset()` as change `useEffect()` to `useLayoutEffect()`.
Closes #2977 .

fix(react): fix useLayoutEffect() to useSafeLayoutEffect()

---

packages/vue/src/components/select/use-select-context.ts

Hey there! 👋🏻 
This PR removes an unnecessary random "1" that was present in the `useSelectContext`. This character does not serve any purpose and should not be in the code.

Remove unnecessary "1" in useSelectContext

---

biome.json

**Issue:**
When committing the code, it got formatted differently than the prettier config does in the IDE.
**Cause:**
In the `lefthook.yml` config file, we have two steps, format and lint. In the format step, prettier is used to format the code.
In the lint step, biome is used to check for linting errors, biome does also have a formatter. Which does format the code and overwrites the changes prettier did in the format step.
**Fix:**
Fixed this by disabling the formatter in Biome.js to not conflict with prettier.
```json
"formatter": {
"enabled": false
}
```
**Question:**
Do we want to run `format` and `lint` now on the whole repo to align everything? If I do, I do have 81 file changes

Fix: Disable the formatter in biome

---

bun.lock
packages/react/package.json
packages/react/vite.config.mts
packages/solid/package.json
packages/solid/vite.config.mts
packages/svelte/package.json
packages/svelte/vite.config.ts
packages/vue/package.json
packages/vue/vite.config.mts

Add vitest v8 test coverage scripts for: react,vue,solid,svelte

feat(packages/*): add vitest test coverage

---

packages/vue/src/components/timer/examples/events.vue
packages/vue/src/components/timer/timer-area.vue
packages/vue/src/components/timer/timer-control.vue

The following timer component would not render timer items inside of `Timer.Area` or the action triggers inside of `Timer.Control` due to the missing slots for those parts, resulting in a empty state (first screenshot).
```vue
<template>
<Timer.Root :targetMs="60 * 60 * 1000">
<Timer.Area>
<Timer.Item type="days" />
<Timer.Separator>:</Timer.Separator>
<Timer.Item type="hours" />
<Timer.Separator>:</Timer.Separator>
<Timer.Item type="minutes" />
<Timer.Separator>:</Timer.Separator>
<Timer.Item type="seconds" />
</Timer.Area>
<Timer.Control>
<Timer.ActionTrigger action="start">Play</Timer.ActionTrigger>
<Timer.ActionTrigger action="resume">Resume</Timer.ActionTrigger>
<Timer.ActionTrigger action="pause">Pause</Timer.ActionTrigger>
</Timer.Control>
</Timer.Root>
</template>
```
By adding …

fix(timer): add missing vue slots

---

CONTRIBUTING.md

Fixing a typo in the CONTRIBUTING.md file: Licesne => License

fix: fix typing in contributing guide

---

packages/vue/src/components/collapsible/collapsible-trigger.vue

closes https://github.com/chakra-ui/ark/issues/3538

fix(vue): missing asChild prop binding on collapsible trigger

---

packages/react/src/components/factory.ts

Closes #3561
We've tested this change by modifying `node_modules`. cf. https://github.com/chakra-ui/ark/issues/3561#issuecomment-3126863671

fix: call `React.isValidElement()` before `Children.only()`
